version: '3.8'
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: elmclient-dev
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 30s
      timeout: 10s
      retries: 3