version: '3.8'
services:
  backend:
    build: .
    container_name: elmboot-backend
    ports:
      - "8080:8080"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
