version: '3.8'
services:
  backend:
    image: maven:3.9.6-eclipse-temurin-11
    container_name: elmboot-backend-dev
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - MAVEN_OPTS=-Xmx1024m
    command: mvn spring-boot:run -Dspring-boot.run.jvmArguments="-Dserver.address=0.0.0.0"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s